# Generated by Django 4.1.7 on 2023-04-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.IntegerField(primary_key=True, serialize=False)),
                ('horacita', models.IntegerField(blank=True, null=True)),
                ('fecha', models.IntegerField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=45, null=True)),
                ('persona_idpersona', models.IntegerField()),
                ('estado_idestado', models.IntegerField()),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('iddia', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('iddieta', models.IntegerField(primary_key=True, serialize=False)),
                ('idempleado', models.CharField(blank=True, max_length=45, null=True)),
                ('planificacion_idplanificacion', models.IntegerField()),
                ('receta_idreceta', models.IntegerField()),
            ],
            options={
                'db_table': 'dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('idejercicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.CharField(blank=True, max_length=45, null=True)),
                ('enfoque_idenfoque', models.IntegerField()),
            ],
            options={
                'db_table': 'ejercicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfoque',
            fields=[
                ('idenfoque', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'enfoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('idevolucion', models.IntegerField(primary_key=True, serialize=False)),
                ('medida_idmedida', models.IntegerField()),
                ('rutina_idrutina', models.IntegerField()),
                ('dieta_iddieta', models.IntegerField()),
                ('fecha', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('idhistoria', models.IntegerField(primary_key=True, serialize=False)),
                ('evolucion_idevolucion', models.IntegerField()),
            ],
            options={
                'db_table': 'historia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=45, null=True)),
                ('horainicio', models.CharField(blank=True, max_length=45, null=True)),
                ('horafin', models.CharField(blank=True, max_length=45, null=True)),
                ('cita_idcita', models.IntegerField()),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idingrediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('racion', models.IntegerField()),
                ('ingredientescol', models.CharField(blank=True, max_length=45, null=True)),
                ('proteinas', models.FloatField(blank=True, null=True)),
                ('carbohidratos', models.FloatField(blank=True, null=True)),
                ('calorias', models.FloatField(blank=True, null=True)),
                ('grasas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('idmedida', models.IntegerField(primary_key=True, serialize=False)),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('indicegrasa', models.IntegerField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, db_column='IMC', null=True)),
            ],
            options={
                'db_table': 'medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('idocupacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ocupacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=45, null=True)),
                ('numid', models.CharField(blank=True, max_length=45, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.IntegerField(blank=True, null=True)),
                ('genero_idgenero', models.IntegerField()),
                ('tipodocumento_idtipodocumento', models.IntegerField()),
                ('cargo_idcargo', models.IntegerField()),
                ('usuario_idusuario', models.IntegerField()),
                ('tipopersona_idtipopersona', models.IntegerField()),
                ('ocupacion_idocupacion', models.IntegerField()),
                ('plan_idmembresia', models.IntegerField()),
                ('historia_idhistoria', models.IntegerField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idmembresia', models.IntegerField(primary_key=True, serialize=False)),
                ('fechainicio', models.IntegerField(blank=True, null=True)),
                ('fechafin', models.IntegerField(blank=True, null=True)),
                ('tipoplan_idtipoplan', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('idplanificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(blank=True, max_length=45, null=True)),
                ('preparacion', models.CharField(blank=True, max_length=45, null=True)),
                ('carbohidratos', models.FloatField(blank=True, null=True)),
                ('calorias', models.FloatField()),
                ('grasas', models.FloatField(blank=True, null=True)),
                ('tipoalimento_idtipoalimento', models.IntegerField()),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('idrepeticion', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'repeticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('idrutina', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_iddia', models.IntegerField()),
                ('ejercicio_idejercicio', models.IntegerField()),
                ('serie_idserie', models.IntegerField()),
                ('repeticion_idrepeticion', models.IntegerField()),
            ],
            options={
                'db_table': 'rutina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idserie', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoalimento',
            fields=[
                ('idtipoalimento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('verduras', models.CharField(blank=True, max_length=45, null=True)),
                ('granos', models.CharField(blank=True, max_length=45, null=True)),
                ('ensaladas', models.CharField(blank=True, max_length=45, null=True)),
                ('bebidas', models.CharField(blank=True, max_length=45, null=True)),
                ('frutas', models.CharField(blank=True, max_length=45, null=True)),
                ('ingrediente_idingrediente', models.IntegerField()),
            ],
            options={
                'db_table': 'tipoalimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocomida',
            fields=[
                ('idtipocomida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('desayuno', models.CharField(blank=True, max_length=45, null=True)),
                ('almuerzo', models.CharField(blank=True, max_length=45, null=True)),
                ('mediatarde', models.CharField(blank=True, max_length=45, null=True)),
                ('cena', models.CharField(blank=True, max_length=45, null=True)),
                ('entrenoche', models.CharField(blank=True, max_length=45, null=True)),
                ('ingrediente_idingrediente', models.IntegerField()),
            ],
            options={
                'db_table': 'tipocomida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipodoc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopersona',
            fields=[
                ('idtipopersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipopersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoplan',
            fields=[
                ('idtipoplan', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipoplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('clave', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
